# Generated by Django 5.1.3 on 2024-11-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="iv",
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="salt",
            field=models.BinaryField(null=True),
        ),
    ]
